### ISSUE TITLE
Can't build a project

### ISSUE THREAD

**Issue by zaur** [lucasr/probe#18]
Hey,
I'm trying to add Probe to my project and get this error:
/Users/Zaur/Projects/android/MyListView/app/build/generated/source/probe/debug/ru/agamov/mylistview/probe/ProbeProxy$android_widget_DateTimeView.java
Error:(8, 22) error: cannot find symbol class DateTimeView
Error:(9, 67) error: cannot find symbol class DateTimeView
Error:(20, 19) error: method onMeasure in class Interceptor cannot be applied to given types;
required: View,int,int
found: ProbeProxy$android_widget_DateTimeView,int,int
reason: actual argument ProbeProxy$android_widget_DateTimeView cannot be converted to View by method invocation conversion

Here is my build.gradle:

``` java
apply plugin: 'com.android.application'
apply plugin: 'org.lucasr.probe'

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'org.lucasr.probe:gradle-plugin:0.1.3'
    }
}

android {
    compileSdkVersion 22
    buildToolsVersion "22.0.1"

    defaultConfig {
        applicationId "ru.agamov.mylistview"
        minSdkVersion 14
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

        debug {
            minifyEnabled false
        }
    }
}

probe {
    buildVariants {
        debug {
            enabled = true
        }
    }
}
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.2.0'
}
```

**Comment by ahmedre** [comment]
ran into the same issue today, this is caused by appcompat-v7 (removing it fixes this issue). the reason is because `DateTimeView` is `@hide` in the framework, whereas `appcompat-v7` uses it in `appcompat/res/layout/notification_template_part_time.xml`.

**Comment by zaur** [comment]
Thanks @ahmedre !

**Comment by zsweigart** [comment]
So does this mean that probe will not be useful for any apps that use appcompat-v7?
